### ISSUE TITLE
We should start caching strings, instead of copying them all around

### ISSUE THREAD

**Issue by Yoric** [fxbox/taxonomy#11]
Many Strings will appear several times (e.g. tags). To avoid copying them, we should use a mechanism of atoms, that makes sure we only have one instance of the String in memory at any given time.

**Comment by Yoric** [comment]
@SimonSapin has developed [a crate for this](https://crates.io/crates/string_cache). We should start using it for:
- `Id<T>`;
- tags.

Given that the crate is pretty much not documented, this may mean documentation work, too.

**Comment by SimonSapin** [comment]
(I’m more or less the maintainer of that crate these days, but it was developed by @ glennw and @ kmcallister.)

Yes, docs need work. In the meantime, the main APIs are `Atom::from(&str) -> Atom`, `Atom` dereferences to `str`, and comparing or hashing atoms is fast (it compares/hashes `u64`’s).

**Comment by azasypkin** [comment]
Hey @SimonSapin,

I see that `string_cache` crate includes a huge list of predefined atoms that look specific to Servo [1].

Is it included in final binary for every consumer of this crate? If so, is it possible to override it somehow?

Thanks!

[1] https://github.com/servo/string-cache/blob/master/src/static_atom_list.rs

**Comment by SimonSapin** [comment]
@azasypkin Currently yes they’re included and no you can’t change them. There are plans to make `Atom` generic so that each user-defined "kind" of atom has its own list of static strings: https://github.com/servo/string-cache/issues/22 and https://github.com/servo/string-cache/pull/136

**Comment by azasypkin** [comment]
Okay, got it, thanks!

**Comment by Yoric** [comment]
Well, first part has landed.
