### ISSUE TITLE
Value::Bool is unhealthy

### ISSUE THREAD

**Issue by Yoric** [fxbox/taxonomy#13]
At the moment, we have a variant `Value::Bool`, which is used for determining whether a door is opened, a device is on, etc. That's ambiguous.

Rather, we should have:
- `Value::Opening(Opening)` with `enum Opening { Open, Closed }`;
- `Value::OnOff(OnOff)`, with `enum OnOff { On, Off }`;
- ...
- and finally `Value::ExtBool`, with the same kind of structure as `Value::ExtNumeric`.

**Comment by azasypkin** [comment]
Okay, finished reading Taxonomy source and ready to actually do something :)

**Comment by guyzmo** [comment]
Hello, as I'm currently discovering the project, and while reading the doc, it struck me that `OnOff` is not a really good name. It'd be a good idea to use the English word used for something that changes between two states: the `toggle` ☺

HTH

**Comment by Yoric** [comment]
@guyzmo Sorry about the silence, hadn't seen your message. In this case, `toggle` might not be a good choice either, because it could be a toggle between three or more states.

**Comment by guyzmo** [comment]
Err… not being a native english, correct me if I'm wrong, but it's unlikely that a toggle is between more than two states, as a _toggle_ is:
- [_" 7. to shift back and forth between two settings or modes of computer operation by means of a key or programmed keystroke. "_](http://www.thefreedictionary.com/toggle) 
- [_to alternate between two positions using a single switch or lever._](https://en.wiktionary.org/wiki/toggle)
- [_to switch between alternate states._](https://en.wiktionary.org/wiki/toggle)

if it has more than two states, then it's only a state machine (a toggle being a 2-state state machine).

**Comment by Yoric** [comment]
Fair enough. Anyway, this bug has been fixed a long time ago.
