### ISSUE TITLE
The mimetype should be an `Id`, rather than a `String`.

### ISSUE THREAD

**Issue by Yoric** [fxbox/taxonomy#18]
There will probably be very few distinct mimetypes in the system, and we don't want to confuse a mimetype string with something else.

So, in `values.rs`, in the definition of `Binary`, we should use `Id<MimetypeId>` instead of `String` for the mimetype. This way, once issue #11 has landed, we'll benefit automatically from string caching.

**Comment by hfiguiere** [comment]
According to commit cd4bf669 this is already done. @Yoric ?

**Comment by Yoric** [comment]
Right, thanks,
