### ISSUE TITLE
Tags should be Id<TagId>

### ISSUE THREAD

**Issue by Yoric** [fxbox/taxonomy#20]
Currently, we represent tags as `String`. For performance, safety and memory usage, we should rather represent them using `Id`.

For this purpose:
1/ Define in `devices.rs` an empty type `struct TagId;`
2/ Find all occurrences of tags as `String` and replace them with `Id<TagId>`.

**Comment by hfiguiere** [comment]
This is fixed with PR #22, isn't it? @Yoric

**Comment by fabricedesre** [comment]
Yes, sorry I should have closed that one.
