### ISSUE TITLE
It should be possible to call AdapterManager methods inside other AdapterManager methods/callbacks

### ISSUE THREAD

**Issue by azasypkin** [fxbox/taxonomy#45]
Live example:
- `AdapterManager` calls `Adapter::send_values` to process setter request;
- `Adapter::send_values` calls `AdapterManager.get_services` to figure out what service this setter belongs to.

**Comment by Yoric** [comment]
I have two ways to do this:
1. the hard-to-write, performant and sandboxed way, in which the `AdapterManagerHandle` seen by an `Adapter` only lets the adapter view and (un)register its own services and channels;
2. the less performant, easier-to-not-screw-up-for-me and easier-to-screw-up for other developers way, in which we handle better the Mutex but each adapter could see and remove other adapter's devices.

**Comment by Yoric** [comment]
I will probably go ahead with option 2. Probably not today, though.
