### ISSUE TITLE
register_watch should take &mut self

### ISSUE THREAD

**Issue by julienw** [fxbox/taxonomy#49]
When calling register_watch we likely need to modify some internal structures. For this "&mut self" is necessary, or we'll need to use a Cell which is very inconvenient -- and could be dangerous.

**Comment by Yoric** [comment]
Well, with commit 9877a2c, `Adapter`s need to become `Sync`, which pretty much means that they can't use `&mut self`. All mutable state will need to be protected behind a `Mutex` or a `RwLock`.

So that probably won't happen.

**Comment by julienw** [comment]
ok
