### ISSUE TITLE
I'm not seeing a String ChannelKind.

### ISSUE THREAD

**Issue by dhylands** [fxbox/taxonomy#72]
Does this mean I have to create a custom kind to store strings?

For example, I need to add getters and setters to the camera to get/set the camera_name, the username and password, and we should probably have a location as well.

**Comment by Yoric** [comment]
`ChannelKind` is _not_ about types but about feature discovery. So, the variants should rather be `Name`, `Password`, `Location`, all of them implemented as `String`.

Does this make sense to you?

**Comment by dhylands** [comment]
Yeah - that makes sense. I'll add those to the taxonomy.
