### ISSUE TITLE
We need a way to properly shutdown the adapters

### ISSUE THREAD

**Issue by julienw** [fxbox/taxonomy#74]
Currently drop functions are not called. This is likely because we don't stop the several threads we're running. One way to do this is to make the SHUTDOWN_FLAG public so that every threads can access it. But it wouldn't be nice for adapters that are in separate repositories.

Another way is to use a "stop" method on adapters, that would be called at the right time.

The openzwave adapter badly needs this.

**Comment by Yoric** [comment]
What's `SHUTDOWN_FLAG`?

I'll add a `stop` method.

**Comment by julienw** [comment]
I was refering https://github.com/fxbox/foxbox/blob/28b7a54d88f8fd3aad527cca335edfccf6cbdf64/src/main.rs#L170
