### ISSUE TITLE
Add a test script to rebuild everything

### ISSUE THREAD

**Issue by Yoric** [fxbox/taxonomy#77]
A few days ago, a problem on Taxonomy (on a personal branch, moreover), caused breakage on Foxbox for everyone.

To solve this issue – and get rid of all the problems we have with pinning Taxonomy – we need a script that gets Travis to rebuild Foxbox with a version of Taxonomy _before we merge that version_. This would considerably simplify the work of updating Taxonomy.

@JohanLorenzo Could you handle that?

**Comment by JohanLorenzo** [comment]
Discussion moved to https://github.com/fxbox/RFC/pull/13
